kind: wasmer.io/App.v0
app_id: da_nkPI5tJUPo8l
name: Animem-test
owner: mosinjonovjasurbek00
package: .
env:
  NODE_ENV: "production"
  PORT: "8080"
  SUPABASE_DB_HOST: "aws-0-ap-northeast-2.pooler.supabase.com"
  SUPABASE_DB_PORT: "6543"
  SUPABASE_DB_USER: "postgres.bkvowaestqzxwlrhkbhk"
  SUPABASE_DB_PASSWORD: "animemuz_200"
  SUPABASE_DB_NAME: "postgres"
  WASMER_DB_HOST: "psql.fr-roub1.bengt.wasmernet.com"
  WASMER_DB_PORT: "20184"
  WASMER_DB_USER: "user_82ffe893"
  WASMER_DB_PASSWORD: "pw_1DuID9AO03FagRCGyr9cBuO13NCui0wd"
  WASMER_DB_NAME: "Animem"
  JWT_SECRET: "anime_super_secret_key"
